version: '3.8'

services:
  postgres:
    container_name: football_management
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: football_management
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres